---
name: 'Terraform FMT'

on: [pull_request]

jobs:
  terraform:
    name: 'Terraform FMT'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Get off Head
        id: checkout_branch
        run: git checkout "${GITHUB_REF:11}"

      - name: Setup Terraform
        id: setup
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        id: fmt
        run: |
          terraform fmt -recursive
          git config user.name ${{ github.actor }}
          git config user.email "devops@2u.com"
          git commit -a -m "[√] Auto-Formatted Terraform"
          git push

      - uses: actions/github-script@v3
        if: github.event_name == 'pull_request' && steps.fmt.outputs.exitcode == 0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const CODE = '```';
            const STATUS = ":white_check_mark: Auto Formatted Files"

            const output = `
            ### Terraform FMT
            ${STATUS}
            <details>
            <summary>Output</summary>

            ${CODE}
            ${{ steps.fmt.outputs.stdout }}
            ${CODE}

            </details>`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      - name: End Result
        shell: bash
        run: |
          test ${{ steps.fmt.outputs.exitcode }} -eq 0

