---
name: 'Terraform FMT'

on: [pull_request]

jobs:
  terraform:
    name: 'Terraform FMT'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        id: setup
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive -diff
        continue-on-error: true

      - uses: actions/github-script@v3
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const CODE = '```';
            const output = `
            ### Terraform FMT
            Status: <span style="color:yello">${{ steps.fmt.outcome }}</span>
            <details>
            <summary>Output</summary>

            ${CODE}
            ${{ steps.fmt.outputs.stdout }}
            ${CODE}

            </details>`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
